exports.DataTabelDepartement = [
  {
    id: 1,
    task: "Inspeksi Kapal Eksplorasi",
    priority: "Prioritas 1",
    status: "Pending",
    download: "https://google.drive",
    submit: "https://google.drive",
    notes: "Tolong baca file panduan ini sebelum inspeksi",
  },
  {
    id: 2,
    task: "Dokumentasi Alat-alat Eksplorasi",
    priority: "Prioritas 3",
    status: "Done",
    download: "https://google.drive",
    submit: "https://google.drive",
    notes: "-",
  },
  {
    id: 3,
    task: "Perjanjian Vendor Alat-alat Eksplorasi",
    priority: "Prioritas 1",
    status: "Done",
    download: "https://google.drive",
    submit: "https://google.drive",
    notes: "-",
  },
  {
    id: 4,
    task: "Instalasi Alat-alat Eksplorasi",
    priority: "Prioritas 1",
    status: "Done",
    download: "https://google.drive",
    submit: "https://google.drive",
    notes: "H-1 harus sudah beres",
  },
  {
    id: 5,
    task: "Alat Kemanan dan Keselamatan Kerja",
    priority: "Prioritas 4",
    status: "Done",
    download: "https://google.drive",
    submit: "https://google.drive",
    notes: "H-1 harus sudah beres",
  },
];
