exports.DataDummy = [
  {
    id: 1,
    name: "Soleh Solihun",
    departemen: "Human Resource",
    start: "08:00 WIB",
    break: "1 jam",
    finish: "17:00 WIB",
    status: "Tepat waktu",
  },
  {
    id: 2,
    name: "Abdul Razak",
    departemen: "Human Resource",
    start: "08:00 WIB",
    break: "1 jam",
    finish: "17:00 WIB",
    status: "Tepat waktu",
  },
  {
    id: 3,
    name: "Thalib",
    departemen: "Human Resource",
    start: "08:30 WIB",
    break: "1 jam",
    finish: "17:30 WIB",
    status: "Tepat waktu",
  },
  {
    id: 4,
    name: "Sunanto Subgio Al Jaza",
    departemen: "Marketing & Business Development",
    start: "08:30 WIB",
    break: "1 jam",
    finish: "17:20 WIB",
    status: "Tidak Tepat waktu",
    style: "text-red-500 font-semibold",
  },
  {
    id: 5,
    name: "Abdur",
    departemen: "Human Resource",
    start: "08:30 WIB",
    break: "1 jam",
    finish: "17:50 WIB",
    status: "Tidak Tepat waktu",
    style: "text-red-500 font-semibold",
  },
  {
    id: 6,
    name: "Abdur Al Abuni Syarif Abu",
    departemen: "Human Resource",
    start: "08:30 WIB",
    break: "1 jam",
    finish: "17:50 WIB",
    status: "Tidak Tepat waktu",
    style: "text-red-500 font-semibold",
  },
];
